### ISSUE TITLE
Support tsx file ext

### ISSUE THREAD

**Issue by abdavid** [Specifyapp/parsers#114]
https://github.com/Specifyapp/parsers/blob/8e92272ea719d795f74af8111c6c77ed5d587580/parsers/svg-to-jsx/svg-to-jsx.parser.ts#L160

It would be nice to be able to specify (no pun intended) that parser should output files with tsx extensions, for those of us that use pure TypeScript projects.

**Comment by abdavid** [comment]
Obviously one could use the `name-assets-files-by-pattern` parser, so I guess this is not really that high of a priority, though it seems like an unnecessary overhead to apply yet another parser because one is quite opinionated. 

If you want you may close this issue since there is a work around. 

```
{
  "name": "name-assets-files-by-pattern",
  "options": {
     "pattern": "{{name}}.tsx"
  }
},
```

**Comment by AMoreaux** [comment]
Hi  @abdavid ,

Thanks for the proposal. It's a good idea 👍
I'll open a PR soon to add an option `isTsx: boolean` in the parser.
