### ISSUE TITLE
No token name transformation for to-theme-ui

### ISSUE THREAD

**Issue by Aktanee** [Specifyapp/parsers#123]
Hello 👋 It will be nice to not have a `formatName`default for `to-theme-ui` parsers. 

We have a token base name with `/` inside (e.g. `text/inverse/twoWords`) that we want to transform to be an object. It's easier to do with the `/` still present inside the name convention. `snakeCase` will transform it to be `text_inverse_two_words`, and we want to keep the `twoWords` in the string.

**Comment by AMoreaux** [comment]
Hi @Aktanee 
To be clear, you would like an output from specify like:
```js
{
  "text": {
    "text/inverse/twoWords": {
      "fontFamily": "you-font-family"
    }
  }
}
```
And after you would like to run another function to generate something like:
```
{
  "text": {
    "inverse": {
      "twoWords": {
        "fontFamily": "you-font-family"
      }
    }
  }
}
```
I'm right?

**Comment by Aktanee** [comment]
Yes :) I already have the code that will create the object according to my own rule using the default JSON return

**Comment by Aktanee** [comment]
This sound like a good solution, thanks :)

**Comment by Aktanee** [comment]
Thanks :)

**Comment by AMoreaux** [comment]
> Thanks :)

You're welcome. It will be deployed in a few minutes.
