### ISSUE TITLE
replace-string: _.get(...).replace is not a function

### ISSUE THREAD

**Issue by alecmarcus** [Specifyapp/parsers#136]
I'm running a `replace-string` parser on the output of an `svg-to-jsx` parser. Here's my rule:

```json
    {
      "name": "React Native SVGs",
      "path": "assets/icons/react-native/",
      "parsers": [
        {
          "name": "svg-to-jsx",
          "options": {
            "prepend": "import React from 'react';\nimport Svg, { Defs, G, LinearGradient, ClipPath, Path, Rect, Circle, Stop } from \"react-native-svg\";",
            "variableFormat": "camelCase",
            "formatConfig": {
              "isTsx": true,
              "useTabs": false
            }
          }
        },
        {
          "name": "replace-string",
          "options": {
            "keys": ["value", "content"],
            "regex": {
              "pattern": "(svg>+)",
              "flags": "gm"
            },
            "replaceBy": "Svg>"
          }
        }
      ]
    }
```

And on `specify pull` I get:
```
replace-string: _.get(...).replace is not a function
```

I've tried omitting `replaceBy` to no avail.

**Comment by AMoreaux** [comment]
Hi @alecmarcus 
For the keys property of replace-string try to use ["value.content"] instead of ["value", "content"]

**Comment by alecmarcus** [comment]
@AMoreaux You caught me as I was commenting my realization here. Thank you!

**Comment by alecmarcus** [comment]
@AMoreaux Is there a way to perform regex or JS operations on the matched string in `replaceBy`? Eg, capitalize it.

**Comment by AMoreaux** [comment]
Today it's not possible with `replace-string`. But could you explain the entire flow you would like to have? I might suggest other parsers to satisfy your expectation.

**Comment by AMoreaux** [comment]
Ok, I see. @robrechtme created a parser [to-react-native](https://github.com/Specifyapp/parsers/tree/master/parsers/to-react-native#guides). 
In the readme, he explains how he uses vector with react-native. I think it could solve your use case.

**Comment by robrechtme** [comment]
I recommend to use the parser with [`react-native-svg-transformer`](https://github.com/kristerkari/react-native-svg-transformer), as mentioned in the "Rendering vectors" part under [Guides](https://github.com/Specifyapp/parsers/tree/master/parsers/to-react-native#guides). 

If you want more info on using Specify with React Native, I wrote a [blog post](https://dev.to/inthepocket/from-figma-to-react-native-using-specify-2ogd) about it 🙂.

**Comment by alecmarcus** [comment]
Thank you, @robrechtme ! 

I'm using that parser and having an issue with pathing.

My file structure is:
```
mobile/
| assets/
| | fonts/
| | vectors/
| themes.ts
```

And my `.specifyrc.js`:
```
    {
      name: "Download Fonts",
      path: "./assets/fonts",
      filter: { types: ["font"] },
    },
    {
      name: "Create Tokens",
      path: "./themes.ts",
      parsers: [
        {
          name: "to-react-native",
          options: {
            assetsFolderPath: {
              vector: "./assets/vectors",
            },
          },
        },
      ],
    },
```

In `themes.ts`, the imports, being normalized by `path.join`, are:
```
import assetVector from "assets/vectors/vector.svg";
```

which doesn't resolve in my RN setup. It must be:

```
import assetDAppsApp from "./assets/vectors/dAppsApp.svg";
```

Can't seem to inform the parser as to how to output the proper path.

**Comment by robrechtme** [comment]
That's a bug indeed, great catch! I didn't know `path.join` would strip `'./'`. 

Feel free to create a PR and tag me. 😊 The issue is with `path.join` [here](https://github.com/Specifyapp/parsers/blob/master/parsers/to-react-native/tokens/vector.ts#L26) and same for [bitmaps](https://github.com/Specifyapp/parsers/blob/master/parsers/to-react-native/tokens/bitmap.ts#L24). In the meantime, you could work around the bug, by e.g. moving your theme to `theme/index.ts` and changing the `assetsFolderPath` to ` "../assets/vectors"`.

**Comment by alecmarcus** [comment]
@robrechtme yeah, pathing out and back in was my workaround. I'd love to help out when I have the time — we'll see 😅 

Thanks!

**Comment by AMoreaux** [comment]
Hi @alecmarcus 
We just released the fix on to-react-native. 
Tell me if it works for you now 🙂
