### ISSUE TITLE
to-jss - using kebabCase as `formatName` leads to keys in object not being quoted

### ISSUE THREAD

**Issue by ArTiSTiX** [Specifyapp/parsers#138]
The JSS parser is throwing an error if we use formatName = `kebabCase` because the `textStyle` token is formatted as :

```javascript
const theme = {
    text-style: {
       'quoted-token': { ... }
    },
    ...
};

export default theme;
```

Token key in root object should also be quoted.

**Comment by AMoreaux** [comment]
Hi @ArTiSTiX 

Thanks for the report. I open a PR to fix that. I tell you when it will be merged and deployed.

Moreover, we released a beta version of the new CLI: https://www.npmjs.com/package/@specifyapp/cli/v/1.0.0-beta.1

Feel free to test it and let us feedback 🙂

**Comment by AMoreaux** [comment]
Hi @ArTiSTiX ,
The fix was released 🙂
