### ISSUE TITLE
[to-tailwind] Box shadow conversion invalid when using nested structures and splitBy

### ISSUE THREAD

**Issue by abdavid** [Specifyapp/parsers#162]
Consider the following configuration:

```
[
   {
      "name":"Tailwind (color,textStyle,measurement,font,shadow)",
      "path":"tokens/web/tailwind/tailwind.config.js",
      "filter":{
         "types":[
            "color",
            "textStyle",
            "measurement",
            "font",
            "shadow"
         ]
      },
      "parsers":[
         {
            "name":"to-tailwind",
            "options":{
               "formatConfig":{
                  "module":"commonjs"
               },
               "formatTokens":{
                  "colorFormat":{
                     "format":"rgb"
                  },
                  "fontSizeFormat":{
                     "unit":"rem"
                  }
               },
               "formatName":"kebabCase",
               "splitBy":"/"
            }
         }
      ]
   }
]
```

Run with the following command with a shadow token in the referenced repository
```
yarn specify pull -r @ruter-as/core -p **<redacted>** -R '[{"name":"Web / Code / Tailwind (color,textStyle,measurement,font,shadow)","path":"tokens/web/tailwind/tailwind.config.js","filter":{"types":["color","textStyle","measurement","font","shadow"]},"parsers":[{"name":"to-tailwind","options":{"formatConfig":{"module":"commonjs"},"formatTokens":{"colorFormat":{"format":"rgb"},"fontSizeFormat":{"unit":"rem"}},"formatName":"kebabCase","splitBy":"/"}}]}]'
```

With a shadow token in the repo, The boxShadow conversion for the to-tailwind parser yields the following which does not work with latest tailwind. 
```
boxShadow: {
    dark: {
       float: "0px 2px 20px rgba(14, 15, 22, 0.08)",
       raised: "0px 2px 4px rgba(14, 15, 22, 0.08)",
    },
    light: {
       float: "0px 2px 20px rgba(49, 54, 99, 0.08)",
       raised: "0px 2px 4px rgba(49, 54, 99, 0.08)"
    },
},
```

while the following works
```
boxShadow: {
   "dark-float": "0px 2px 20px rgba(14, 15, 22, 0.08)",
   "dark-raised": "0px 2px 4px rgba(14, 15, 22, 0.08)",
   "light-float": "0px 2px 20px rgba(49, 54, 99, 0.08)",
   "light-raised": "0px 2px 4px rgba(49, 54, 99, 0.08)",
},
```

**Comment by AllanMichay** [comment]
If I understand correctly, the problem seems to come from Shadow tokens with names like `Dark/Float` right?

For now, you can create a new rule for shadow tokens that do not apply the `splitBy`.

As an example, this is what the configuration would look like :

```json
[
	{
		"name":"Tailwind (color,textStyle,measurement,font)",
		"path":"tokens/web/tailwind/tailwind.theme.js",
		"filter":{
				"types":[
					"color",
					"textStyle",
					"measurement",
					"font"
				]
		},
		"parsers":[
				{
					"name":"to-tailwind",
					"options":{
						"formatConfig":{
							"module":"commonjs"
						},
						"formatTokens":{
							"colorFormat":{
									"format":"rgb"
							},
							"fontSizeFormat":{
									"unit":"rem"
							}
						},
						"formatName":"kebabCase",
						"splitBy":"/"
					}
				}
		]
	},
	{
		"name":"Tailwind (shadow)",
		"path":"tokens/web/tailwind/tailwind.shadows.js",
		"filter":{
				"types":[
					"shadow"
				]
		},
		"parsers":[
				{
					"name":"to-tailwind",
					"options":{
						"formatConfig":{
							"module":"commonjs"
						},
						"formatTokens":{
							"colorFormat":{
									"format":"rgb"
							},
							"fontSizeFormat":{
									"unit":"rem"
							}
						},
						"formatName":"kebabCase"
					}
				}
		]
	}
]
```

This will create two js files (`tailwind.theme.js` and `tailwind.shadows.js`) that you can import into your `tailwind.config.js` and use to extend your theme.

This is a short-term solution that will allow you to use Specify, we are looking for a more long-term solution so that you can do this with one rule.

We were thinking of changing the to-tailwind parser to not apply the splitBy on it (since it seems there is no reason for this to be applied).

Another one of our potential solutions would be to be able to use our `replace-string`parser on some specific types only. This way, you could remove the `/ ` on your tokens for this specific rule.

Which of these two solutions would be preferable for you?

1️⃣ Stop applying splitBy on shadows
2️⃣ Give replace-string more controls over which type to apply

**Comment by abdavid** [comment]
Thank you for your explanation @AllanMichay  

I will look in to the alternatives you list here. 

What are you planning on the token front? It would be nice to have something like transforms in style-dictionary so we may apply specific transforms to a token in the same pipe.

**Comment by AllanMichay** [comment]
Thanks, @abdavid, tell me if you have any questions about the alternatives.

I'm not sure I fully understand what you're asking for. IMO, it feels like our parsers and style-dictionary transforms are pretty identical. Our parsers act as predetermined transforms. However, they do not have specific categories, unlike transforms.

Do you want to be able to apply some parsers on a specific token type? Is that what you're asking for? Do you have an example of what you would want to be able to do?

**Comment by abdavid** [comment]
@AllanMichay I understand.

This pseudo configuration would probably illustrate what I am thinking of.

```json
{
  "name":"Tailwind", //pipeline name
  "tokens": [ // Tokens I want to work with in this pipeline
    "color",
    "textStyle",
    "measurement",
    "font",
    "shadow"
  ],
  "tranforms":[ // Token tranformations before getting passed to the output format. Here one would apply all non-file outputting parsers
    {
      "name": "kebabcasify",
      "options": {
        "tokens": [
          "shadow" // the token category I want to apply this specific parser to
        ],
        "keys": ["name"]
      }
    },
    ...
  ],
  "output": { //pipeline output configuration basically all file-outputting parsers would be considered an output
    "format": "tailwind", // the to-* parsers "tailwind | style-dictionary | dsp | css-custom-properties | flutter | react-native | scss-variables | raw |...."
    "path": "tokens/web/tailwind/tailwind.shadows.js",
    "options":{ // format options
      "formatConfig":{
        "module":"commonjs"
      },
      "formatTokens":{
        "colorFormat":{
          "format":"rgb"
        },
        "fontSizeFormat":{
          "unit":"rem"
        }
      },
      "formatName":"kebabCase",
      "splitBy":"/"
    }
  }
}
```

Given the above configuration one would discern file-outputting and data-outputting transformations, beneficial DX, and I know you have been working a lot on the docs to underscore parser compatibility. non-file outputting parsers here referred to as `tranforms` and can target a specific category, but default would obviously be all tokens defined in pipeline. If you introduce unit tranformations at some point this would also be beneficial so one might mix units (sp dp etc), while also being able to do more with one configuration.

**Comment by AllanMichay** [comment]
Oh okay. Thanks a lot, @abdavid for your feedback and your time. I now understand what you were asking 👍 

I'll get back to the team and keep you posted on this. In the meantime, does the configuration work for Tailwind now?

**Comment by abdavid** [comment]
Yes, alt. 1 resolves the issue for me with a bit of overhead though, but it works 👍🏻
