### ISSUE TITLE
Update documentation for to-scss-map format

### ISSUE THREAD

**Issue by LukasCornille** [Specifyapp/parsers#68]
Hi,

The documentation for the [to-scss-map](https://github.com/Specifyapp/parsers/tree/master/parsers/to-scss-map) parser seems to be outdated.

the color formatting option is defined as:
```ts
colorFormat?: {
    format: "hex";
};
```

But the code specifically requests it to be [the following](https://github.com/Specifyapp/parsers/blob/40b44e7f99a05911c3c02c034eea5179bf11ad0e/parsers/to-scss-map/to-scss-map.parser.ts#L16)
```ts
color?: {
    format: "hex";
};
```

**Comment by AMoreaux** [comment]
Good point! It will be fixed in few minutes 👍
